jobs:
  - name: middleware-scheduler
    type: cron
    env: python
    schedule: "0 */4 * * *"  # Every 4 hours (adjust as needed)
    buildCommand: pip install -r requirements.txt
    startCommand: python start_middleware.py
    envVars:
      - key: TG_BOT_TOKEN
        value: YOUR_TELEGRAM_BOT_TOKEN
      - key: STAGING_CHAT_ID
        value: -1001234567890
