name: Run Middleware On Demand

on:
  workflow_dispatch:  # allows manual run from GitHub UI

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run middleware
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          STAGING_CHAT_ID: ${{ secrets.STAGING_CHAT_ID }}
        run: python start_middleware.py
